imported review changes

diff --git a/.github/workflows/deb-package.yml b/.github/workflows/deb-package.yml
--- a/.github/workflows/deb-package.yml
+++ b/.github/workflows/deb-package.yml
@@ -8,18 +8,15 @@ env:
   DESCRIPTION: BOINC lets you help cutting-edge science research using your computer. The BOINC app, running on your computer, downloads scientific computing jobs and runs them invisibly in the background. It's easy and safe.
   BASEREPO: https://boinc.berkeley.edu/dl/linux # no trailing slash
   GH_REPO_API: BOINC/boinc # no trailing or prefix slash
-  PUBKEY: boinc-202305.gpg # keep extension
+  PUBKEY: boinc.gpg # keep extension
+
+concurrency:
+  group: deb-package
+  cancel-in-progress: true
 
 on:
   workflow_dispatch:
     inputs:
-      package_type:
-        description: 'package type to generate'
-        type: choice
-        options:
-          - linux_client-vcpkg
-          - linux_manager-without-webview
-        required: true
       release_type:
           description: 'release repository type to generate'
           type: choice
@@ -27,16 +24,6 @@ on:
             - alpha
             - stable
           required: true
-      package_main_version:
-        description: 'main version to assign the package'
-        type: string
-        default: "1.0.0"
-        required: true
-      package_build_version:
-        description: 'sequential build number of the package'
-        type: string
-        default: "1"
-        required: true
       build_run_id:
         description: 'workflow run id to download artifacts, default latest one'
         type: integer
@@ -53,23 +40,25 @@ on:
         default: false
         required: true
 
-run-name: DEB publish [${{ inputs.release_type }}][${{ inputs.package_type }}][${{ inputs.package_main_version }}-${{ inputs.package_build_version }}][CanCreate:${{ inputs.allow_repo_create }}][Remove:${{ inputs.remove_package }}]
+run-name: DEB publish [${{ inputs.release_type }}][CanCreate:${{ inputs.allow_repo_create }}][Remove:${{ inputs.remove_package }}]
 
 jobs:
   build:
     name: generate-deb
     runs-on: ubuntu-latest
     strategy:
+      max-parallel: 1
       matrix:
         os: [jammy, focal, bullseye, buster]
+        package-type: [linux_client-vcpkg, linux_manager-without-webview]
     environment:
       name: ${{ inputs.release_type }}
     steps:
       - name: Checkout files
         uses: Bhacaz/checkout-files@v2
         with:
-          files: .github
-          branch: deb-build
+          branch: ${{ github.head_ref || github.ref_name }}
+          files: .github version.h
 
       - name: Preparation
         id: prep
@@ -77,11 +66,18 @@ jobs:
           {
             echo "===== Step Preparation ====="
 
-            # Setup Environment vars
-            PKG_NAME=$(echo "${{ env.PKG_PREFIX }}-${{ inputs.package_type }}" | sed "s|_|-|")
-            PKG_CLEAN=$(echo "$PKG_NAME" | sed "s|-vcpkg||")
-            PKG_FULL="${PKG_CLEAN}_${{ inputs.package_main_version }}-${{ inputs.package_build_version }}_${{ env.ARCH }}"
+            PKG_VERSION=$(cat version.h | grep BOINC_VERSION_STRING | sed -e 's|#define BOINC_VERSION_STRING||' | jq -r .)
+            if [[ "${PKG_VERSION}" -eq "" ]]; then
+              printf "Could not obtain release package version from version.h"
+              exit 1
+            fi
 
+            # Setup Environment vars
+            PKG_NAME=$(echo "${{ env.PKG_PREFIX }}-${{ matrix.package-type }}" | sed "s|_|-|")
+            PKG_CLEAN=$(echo "$PKG_NAME" | sed "s|-vcpkg||")
+            PKG_FULL="${PKG_CLEAN}_${PKG_VERSION}-1_${{ env.ARCH }}"
+
+            echo "PKG_VERSION=${PKG_VERSION}" >> $GITHUB_ENV
             echo "PKG_NAME=${PKG_NAME}" >> $GITHUB_ENV
             echo "PKG_CLEAN=${PKG_CLEAN}" >> $GITHUB_ENV
             echo "PKG_FULL=${PKG_FULL}" >> $GITHUB_ENV
@@ -89,6 +85,7 @@ jobs:
 
             echo "Orig. Package name ${PKG_NAME}"
             echo "Package name ${PKG_CLEAN}"
+            echo "Package version ${PKG_VERSION}"
             echo "Full name ${PKG_FULL}"
             echo "Key file ${{ env.PUBKEY }}"
 
@@ -119,8 +116,16 @@ jobs:
             echo "===== Step DownloadArtifacts ====="
 
             # Downloads artifacts of the latest run
-            ID=$(curl -s -XGET "https://api.github.com/repos/${GH_REPO_API}/actions/workflows/linux.yml/runs" | jq .workflow_runs[0].id)
-            URL=$(curl -s -XGET "https://api.github.com/repos/${GH_REPO_API}/actions/runs/$ID/artifacts" | jq -r ".artifacts[] | select(.name==\"${{ inputs.package_type }}_\") | .archive_download_url")
+            ID="${{ inputs.build_run_id }}"
+            TYPE="${{ matrix.package-type }}"
+            if [[ "$ID" -eq "0" ]]; then
+              ID=$(curl -s -XGET "https://api.github.com/repos/${GH_REPO_API}/actions/workflows/linux.yml/runs" | jq .workflow_runs[0].id)
+            fi
+            URL=$(curl -s -XGET "https://api.github.com/repos/${GH_REPO_API}/actions/runs/$ID/artifacts" | jq -r ".artifacts[] | select(.name==\"${TYPE}_\") | .archive_download_url")
+            if [[ "$URL" -eq "" ]]; then
+              printf "Could not find artifact for ${TYPE} in run ${ID}"
+              exit 1
+            fi
             wget -O pkgs/${PKG_NAME}.zip -d --header='Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' $URL
 
           } &>> "${{ github.workspace }}/steps.log"
@@ -131,7 +136,7 @@ jobs:
           {
             echo "===== Step CreateDebFolder ====="
             # Invokes the package preparation
-            bash -x ${{ github.workspace }}/.github/workflows/debrepo/package_prepare.sh "${{ matrix.os }}" "${PKG_FULL}" "${PKG_NAME}" "${{ inputs.package_type }}"
+            bash -x ${{ github.workspace }}/.github/workflows/debrepo/package_prepare.sh "${{ matrix.os }}" "${PKG_FULL}" "${PKG_NAME}" "${{ matrix.package-type }}"
 
           } &>> "${{ github.workspace }}/steps.log"
 
@@ -141,16 +146,16 @@ jobs:
           {
             echo "===== Step CreateDebDefinition ====="
 
-            # Derive the package dependencies for hte selected package / os / release combination selected
+            # Derive the package dependencies for the selected package / os / release combination selected
             cd ${{ github.workspace }}/.github/workflows/debrepo/
-            PKG_DEPS=$(bash package_depends.sh ${{ matrix.os }} ${{ inputs.package_type }})
+            PKG_DEPS=$(bash package_depends.sh ${{ matrix.os }} ${{ matrix.package-type }})
             echo "Dependencies: ${PKG_DEPS}"
 
             # Produce the package DEB definition
             cd "${{ github.workspace }}/${PKG_FULL}"
             echo "Name:${PKG_CLEAN}
           Package:${PKG_CLEAN}
-          Version:${{ inputs.package_main_version }}-${{ inputs.package_build_version }}
+          Version:${{ inputs.package_main_version }}-1
           Maintainer:${{ env.MANTAINER }}
           Depends:${PKG_DEPS}
           Architecture:${{ env.ARCH }}
@@ -254,7 +259,7 @@ jobs:
       - uses: actions/upload-artifact@v3
         if: always()
         with:
-          name: ${{ matrix.os }}-steps-logs
+          name: ${{ matrix.package-type }}-${{ matrix.os }}-steps-logs
           path: "${{ github.workspace }}/steps.log"
 
       # Deployment of the repository for the combination channel / osversion
